name: Download pck

on:
  push:
    branches:
      - main

jobs:
  download-and-extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download File
      run: |
        curl -L -o index.pck "https://download1073.mediafire.com/14o743qxkpmgPyKd5RwUscVCucvmRmh69TA5ENP0gEeel83TstKHb91X68aHOEhK7SALJ1hK0WGdPrMuoqez_8iSOgN2e2FP1QTeS0cB3YVaQhltKZ2Fiow9Fejq_u5C_49xMujQfnx7xoxEPkTAgtSSOK29c8y1HXX4zT63/moigdxocwcf5a1r/index.pck"

    - name: Verify Download
      run: |
        ls -l index.pck

    - name: File Size Check
      run: |
        du -h index.pck
